### ISSUE TITLE
Unable to change state in bookings and orders table

### ISSUE THREAD

**Issue by marfago** [bluedynamics/bda.plone.orders#28]
It is not possiible to change the state as title states.
Given error is:

Traceback (most recent call last):
  File "/home/marco/Plone-Dev/eggs/bda.plone.ajax-1.6-py2.7.egg/bda/plone/ajax/action.py", line 51, in ajaxaction
    ret['payload'] = view()
  File "/home/marco/Plone-Dev/devsrc/bda.plone.orders/src/bda/plone/orders/browser/views.py", line 159, in __call__
    vendor_uids
  File "/home/marco/Plone-Dev/devsrc/bda.plone.orders/src/bda/plone/orders/browser/views.py", line 125, in _do_transition_for_booking
    vendor_uids=vendor_uids,
TypeError: __init__() takes at least 2 arguments (3 given)

I guess that the error is views.py where the instantiation of BookinData and OrderData omits self.context.

**Comment by rnixx** [comment]
Hi. https://github.com/bluedynamics/bda.plone.orders/commit/b77a6d30d5a1605e6c4ff991f549229c979e2818 should fix this. Can you try and close the issue please?

**Comment by marfago** [comment]
No it does not.
PLease do the same for the previous row as well

booking_data = BookingData(uid=uid, vendor_uids=vendor_uids)

is

booking_data = BookingData(self.context, uid=uid, vendor_uids=vendor_uids)

Thx

**Comment by rnixx** [comment]
Oh. missed that one. Thanks! https://github.com/bluedynamics/bda.plone.orders/commit/ecd6997142bde8fa3baa28fa166a2f713c54f48f

**Comment by thet** [comment]
Closed by: https://github.com/bluedynamics/bda.plone.orders/pull/34
