### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by kyholdings** [bluedynamics/bda.plone.orders#61]
Hi
in page @@orders
I want to send notification to customer of selected orders. when click send button display such error:

```
Traceback (most recent call last):
  File "/opt/bda/eggs/bda.plone.ajax-2.0-py3.7.egg/bda/plone/ajax/__init__.py", line 243, in render_ajax_form
    result = context.restrictedTraverse(name)()
  File "/opt/bda/devsrc/bda.plone.orders/src/bda/plone/orders/browser/notify_customers.py", line 135, in __call__
    return self.render_form()
  File "/opt/bda/eggs/yafowil.plone-4.0.0a3-py3.7.egg/yafowil/plone/form.py", line 51, in render_form
    controller = Controller(self.form, self.request)
  File "/opt/bda/eggs/yafowil-2.3.2-py3.7.egg/yafowil/controller.py", line 18, in __init__
    self.data = self.widget.extract(request)
  File "/opt/bda/eggs/yafowil-2.3.2-py3.7.egg/yafowil/base.py", line 468, in extract
    data.extracted = extractor(self, data)
  File "/opt/bda/eggs/yafowil-2.3.2-py3.7.egg/yafowil/compound.py", line 24, in compound_extractor
    child.extract(data.request, parent=data)
  File "/opt/bda/eggs/yafowil-2.3.2-py3.7.egg/yafowil/base.py", line 468, in extract
    data.extracted = extractor(self, data)
  File "/opt/bda/devsrc/bda.plone.orders/src/bda/plone/orders/browser/notify_customers.py", line 75, in validate_tpl
    state, msg = TEMPLATE.validate(data.extracted.decode("utf8"))
AttributeError: 'str' object has no attribute 'decode'
```
Could you please help me to fix the error?

Thanks
Alex

**Comment by agitator** [comment]
fixed in https://github.com/bluedynamics/bda.plone.orders/commit/d26b0bdbc313f0e2f5b33a72f299f0b5c61d6b08
